#!/bin/sh
# ------------------------------------------------------------------
# Generate throwaway secrets for the DEMO profile only.
# ------------------------------------------------------------------
#
# Writes .env and secrets/ferrum-proxy-secret.conf with freshly generated
# values, wired for the disposable gateway in compose.yaml. It refuses to
# overwrite an existing .env, so it can never clobber a real configuration.
#
# Do not use this for production: it puts secrets on disk in the clear and
# points Foundry at a throwaway gateway over plaintext HTTP.

set -eu

cd "$(dirname "$0")"

if [ -e .env ]; then
  echo "refusing to overwrite an existing .env; remove it first" >&2
  exit 1
fi

random() { openssl rand -base64 48 | tr -d '\n='; }

jwt_secret="$(random)"
proxy_secret="$(random)"
basic_auth_secret="$(random)"

umask 077
mkdir -p secrets ca

cat > .env <<ENV
# Generated by bootstrap-demo.sh for the DEMO profile. Throwaway values.
FERRUM_ADMIN_URL=http://demo-gateway:9000
FERRUM_JWT_SECRET=${jwt_secret}
FERRUM_JWT_AUDIENCE=ferrum-admin
FERRUM_NAMESPACE=ferrum-foundry-demo
FERRUM_TRUSTED_PROXY_SECRET=${proxy_secret}
FERRUM_BASIC_AUTH_HMAC_SECRET=${basic_auth_secret}
FERRUM_ENABLE_HSTS=false
FOUNDRY_DEMO_PORT=${FOUNDRY_DEMO_PORT:-8088}
FERRUM_DEMO_PROXY_PORT=${FERRUM_DEMO_PROXY_PORT:-8000}
FERRUM_DEMO_ADMIN_PORT=${FERRUM_DEMO_ADMIN_PORT:-9000}
FOUNDRY_IMAGE=${FOUNDRY_IMAGE:-ferrumedge/ferrum-foundry:main}
ENV

printf 'set $ferrum_proxy_secret "%s";\n' "$proxy_secret" > secrets/ferrum-proxy-secret.conf

echo "Wrote .env and secrets/ferrum-proxy-secret.conf (throwaway values)."
echo "Next: docker compose --profile demo up -d"
