import type { AuditPipelineStatus, LoggingSink } from '@/api/health';
import type { HealthResponse } from '@/api/types';

export const auditPipeline: AuditPipelineStatus = {
  enabled: true, durability: 'spool', policy: 'fail_closed', available: true,
  last_unavailable_reason: 'none', degraded: false, degraded_reason: 'none', evidence_lost: false,
  queue_capacity: 100, spool_max_records: 200, retained_max_records: 50, max_delivery_attempts: 5,
  accepted_total: 0, prepared_total: 0, finalized_total: 0, unknown_outcome_total: 0,
  enqueued_total: 0, delivered_total: 0, retries_total: 0, delivery_failures_total: 0,
  retained_total: 0, replayed_total: 0, corrupt_records_total: 0, destination_mismatch_total: 0,
  truncated_diffs_total: 0, dropped_durable_handoff_failed_total: 0, dropped_no_durable_spool_total: 0,
  dropped_retained_capacity_total: 0, fail_open_unaudited_mutations_total: 0, fail_closed_rejections_total: 0,
  queue_depth: 0, delivery_in_flight: 0, spool_prepared_records: 0, spool_pending_records: 0, spool_retained_records: 0,
};
export const logSink: LoggingSink = {
  sink: 'stdout', healthy: true, accepting: true, queue_capacity_records: 100, queue_capacity_bytes: 10000,
  max_record_bytes: 1000, queued_records: 2, reserved_bytes: 200, queued_bytes: 200,
  accepted_records_total: 20, saturation_dropped_records_total: 1, oversized_dropped_records_total: 0,
  closed_dropped_records_total: 0, writer_failures_total: 0, flush_failures_total: 0,
  shutdown_timeouts_total: 0, shutdown_incomplete_records_total: 0, last_failure: null,
};
export const detailedHealth: HealthResponse = {
  status: 'ok', ready: true, timestamp: '2026-09-19T12:00:00Z', mode: 'database',
  admin_writes_enabled: true, cached_config: { available: true },
};

/** Deliberately coarse OK with adverse detail: the UI must still surface it. */
export const adverseHealth: HealthResponse = {
  ...detailedHealth,
  gateway_listeners: {
    config_generation: 4, desired_listeners: 3, active_listeners: 1, failed_ports: 2,
    active_failures: 3, retained_failures: 1, truncated: true, overflowed: true,
    active_by_category: [{ protocol: 'quic', category: 'bind_failed', count: 3 }],
    failures: [{ port: 9443, protocol: 'quic', category: 'bind_failed', origin: 'runtime', config_generation: 4,
      detail: 'Address already in use', first_observed_unix_ms: 100, last_observed_unix_ms: 200, observations: 2 }],
  },
  listener_failures: { failures_total: 1, failures: [{ listener: 'cp-grpc', listen_port: 50051, error: 'listener serve task exited after successful bind', kind: 'serve_failed' }] },
  database_polling: { status: 'degraded', reason: 'rejected_incremental_delta', current_backoff_seconds: 30,
    current_backoff_bucket: 'lt_5m', consecutive_identical_rejections: 3,
    change_stream: { enabled: true, connected: false, degraded_reason: 'stream_error', events_total: 3,
      reconnects_total: 1, invalidations_total: 0, history_losses_total: 0, resume_token_retained: true } },
  logging: { stdout: logSink, stderr: { ...logSink, sink: 'stderr', healthy: false, accepting: false,
    last_failure: { operation: 'write', error_kind: 'broken_pipe', occurred_at: '2026-09-19T12:00:00Z' } } },
  log_sink_record_loss: { dropped_total: 7, accepted_total: 30, dropped_by_plugin: { api_chargeback_sink: { queue_full: 7 } } },
  namespace: { active: 'serving-tenant', serving_scope: 'single-namespace-data-plane', data_plane_single_namespace: true },
  jwks_trust: { fresh: 1, grace: 2, expired: 3, max_age_seconds: { fresh: 10, grace: 500, expired: 900 } },
  kafka_logging: [{ generation_id: 2, healthy: false, accepting: false, finalized: false,
    flush_timeout_seconds: 3, max_entry_bytes: 1000, buffer_max_bytes: 10000, retained_bytes: 200,
    admitted_total: 3, delivered_total: 1, delivery_failed_total: 1, queue_rejected_total: 0,
    ferrum_dropped_total: 1, entry_oversize_total: 0, byte_budget_exhausted_total: 0,
    flush_failures_total: 0, flush_timeouts_total: 0, shutdown_incomplete_total: 0, in_flight: 1, last_failure: null }],
  ai_transcript_audit: [{ instance_id: 1, sink_healthy: false, max_request_bytes: 1024, max_response_bytes: 1024,
    max_stream_capture_bytes: 1024, hard_max_request_bytes: 1048576, hard_max_response_bytes: 1048576,
    hard_max_stream_capture_bytes: 1048576, hard_max_capture_bytes_aggregate: 2097152, max_model_bytes: 256,
    max_tool_names: 64, max_tool_name_bytes: 128, max_tool_names_aggregate_bytes: 4096,
    max_retained_record_bytes: 4096, max_redaction_scan_bytes: 10000, max_entry_bytes: 10000,
    max_entry_retained_bytes: 20000, buffer_max_bytes: 100000, retained_bytes: 30, retained_byte_drops: 2,
    max_stream_reservation_secs: 900, stream_reservations_expired: 1, stream_hash_scope: 'capped',
    ack_policy: 'drain', ack_max_bytes: 65536, ack_timeout_ms: 1000 }],
  audit_pipeline: { ...auditPipeline, available: false, degraded: true, evidence_lost: true,
    last_unavailable_reason: 'spool_saturated', degraded_reason: 'retained_capacity',
    fail_closed_rejections_total: 4, dropped_retained_capacity_total: 2 },
  service_discovery: { tasks: 1, running: 0, restarting: 1, crash_looping: 0, stale: 1, withdrawn: 0,
    readiness_failing: 1, never_succeeded: 0, max_anchor_age_seconds: 600,
    upstreams: [{ upstream: 'orders', provider: 'dns', state: 'restarting', stale: true, withdrawn: false,
      policy: 'fail_readiness', max_stale_seconds: 300, last_success_age_seconds: 600, anchor_age_seconds: 600,
      consecutive_failures: 2, consecutive_crashes: 1, restarts: 1, last_error: 'task_exited' }] },
  cp_dp_trust: { configured: true, worker_state: 'stalled', worker_running: true, degraded: true, stale: true,
    admission_blocked: true, readiness_blocked: true, reason: 'reload_read_timed_out', last_attempt_age_seconds: 600,
    last_acceptance_age_seconds: 650, max_stale_seconds: 300, unbounded_stale_allowed: false,
    consecutive_failures: 2, recoveries_total: 1, attempts_total: 4, acceptances_total: 2, rejections_total: 2,
    active_generation: 'test-generation', rejections_by_reason: { reload_read_timed_out: 2 } },
  dp_config: { stale: true, reason: 'snapshot_stale', stale_action: 'fail_closed', new_traffic_blocked: true,
    cp_connected: false, cp_authority: 'lost', cp_disconnected_seconds: 600, max_stale_seconds: 300,
    applied_snapshot: true, snapshot_age_seconds: 650, applied_total: 1, rejected_total: 1,
    apply_failed_total: 1, stale_transitions_total: 1, cp_admission_refused_total: 2 },
  replay_authority: { shared_authorities: 2, shared_authorities_unavailable: 1 },
  mesh: {
    egress_scope: { sidecar_admitted_services: 3, sidecar_denied_services: 1 },
    config_stream: { protocol: 'xds', state: 'serving_last_good', last_attempt_outcome: 'transport_failure',
      fallback_active: true, consecutive_failures: 2, credential: 'valid', liveness_bound_seconds: 60 },
    udp_placement_migration: { enabled: true, phase: 'failed', outstanding: 2, failure_reason: 'pod_cleanup_failed',
      established_adoption: true, adoption_proof: 'new_boot' },
    node_waypoint_observability: { enabled: true, missing_destination_metadata: 0, plaintext_fallback_attempts: 0,
      hbone_handshakes: { inbound_tls_success: 5, inbound_tls_failure: 1, inbound_connect_success: 5,
        inbound_connect_failure: 0, outbound_dial_success: 5, outbound_dial_failure: 0 },
      asserted_identity: { accepted: 5, rejected_untrusted_assertor: 0, rejected_assertion_out_of_scope: 0,
        rejected_trust_domain_mismatch: 0, rejected_unauthenticated_hbone: 0, rejected_malformed: 0, rejected_stale_or_unknown: 0 },
      destination_policy_rejections: { authz_deny: 1, scope_missing: 0, destination_scope_missing: 0, relay_destination_denied: 0 } },
  },
};
